### ISSUE TITLE
"URL is not a constructor" when running sample code

### ISSUE THREAD

**Issue by sp4ceman** [CliffS/kraken-exchange#2]
this.url = new URL(`${APIVERSION}/${path}`, API);
                 ^

TypeError: URL is not a constructor
    at KrakenPrivate.KrakenAPI (C:\dev\red5\node_modules\kraken-exchange\lib\local\KrakenAPI.js:23:18)
    at KrakenPrivate (C:\dev\red5\node_modules\kraken-exchange\lib\local\KrakenPrivate.js:30:7)
    at Kraken.balance (C:\dev\red5\node_modules\kraken-exchange\lib\kraken.js:157:14)
    at Object.<anonymous> (C:\dev\red5\main.js:8:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by CliffS** [comment]
What version of NodeJS are you using?  Maybe it can't cope with the syntax:

```javascript
{URL} = require('url');
```

**Comment by sp4ceman** [comment]
you're correct sorry man this was a node version error on my part!
